[project]
name = "mcp-client"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "anthropic>=0.52.2",
    "mcp>=1.9.2",
    "openai>=1.84.0",
    "python-dotenv>=1.1.0",
    "fastapi>=0.110.0",
    "uvicorn>=0.27.1",
]
